ALTER TABLE item_entity CHANGE progressType exposureType VARCHAR(255);
ALTER TABLE item_entity MODIFY COLUMN exposureType VARCHAR(255) NOT NULL;
ALTER TABLE item_entity MODIFY COLUMN image VARCHAR(255) NOT NULL;
ALTER TABLE item_entity MODIFY COLUMN title VARCHAR(255) NOT NULL;
ALTER TABLE item_entity MODIFY COLUMN place VARCHAR(255) NOT NULL;
ALTER TABLE item_entity MODIFY COLUMN latitude VARCHAR(255) NOT NULL;
ALTER TABLE item_entity MODIFY COLUMN longitude VARCHAR(255) NOT NULL;
ALTER TABLE item_entity MODIFY COLUMN regionType VARCHAR(255) NOT NULL;
ALTER TABLE item_entity MODIFY COLUMN fee VARCHAR(255) NOT NULL;